#!/bin/sh
set -e

REPO="toshalkumbhar8979-design/Agent-grep"
BINARY_NAME="agtgrep"

# 1. Detect OS
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$OS" in
  linux*)  OS="linux" ;;
  darwin*) OS="darwin" ;;
  *)
    echo "Error: Unsupported operating system: $OS"
    exit 1
    ;;
esac

# 2. Detect Architecture
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64 | amd64) ARCH="amd64" ;;
  aarch64 | arm64) ARCH="arm64" ;;
  *)
    echo "Error: Unsupported architecture: $ARCH"
    exit 1
    ;;
esac

echo "Detected System: ${OS}/${ARCH}"

# 3. Get latest release tag from GitHub API
echo "Fetching latest release tag for ${REPO}..."
RELEASE_TAG=$(curl -sSL "https://api.github.com/repos/${REPO}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

if [ -z "$RELEASE_TAG" ]; then
  echo "Error: Could not determine latest release tag."
  exit 1
fi

echo "Latest Release Tag: ${RELEASE_TAG}"

# Strip 'v' prefix if present for binary archive naming matching GoReleaser output
VERSION_NUM=$(echo "$RELEASE_TAG" | sed 's/^v//')

# Archive format generated by GoReleaser (e.g. Agent-grep_0.1.0_linux_amd64.tar.gz)
ARCHIVE_NAME="Agent-grep_${VERSION_NUM}_${OS}_${ARCH}.tar.gz"
DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${RELEASE_TAG}/${ARCHIVE_NAME}"

# 4. Download and install
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

echo "Downloading ${DOWNLOAD_URL}..."
curl -sSL "$DOWNLOAD_URL" -o "${TMP_DIR}/${ARCHIVE_NAME}"

echo "Extracting binary..."
tar -xzf "${TMP_DIR}/${ARCHIVE_NAME}" -C "$TMP_DIR"

# Locate executable binary
if [ ! -f "${TMP_DIR}/${BINARY_NAME}" ]; then
  echo "Error: Executable binary '${BINARY_NAME}' not found in archive."
  exit 1
fi

# Move binary to install location
INSTALL_DIR="/usr/local/bin"
echo "Installing ${BINARY_NAME} to ${INSTALL_DIR}..."

if [ -w "$INSTALL_DIR" ]; then
  mv "${TMP_DIR}/${BINARY_NAME}" "${INSTALL_DIR}/${BINARY_NAME}"
else
  echo "Elevated permissions required to write to ${INSTALL_DIR}."
  sudo mv "${TMP_DIR}/${BINARY_NAME}" "${INSTALL_DIR}/${BINARY_NAME}"
fi

chmod +x "${INSTALL_DIR}/${BINARY_NAME}"

echo ""
echo "Successfully installed ${BINARY_NAME} ${RELEASE_TAG} to ${INSTALL_DIR}/${BINARY_NAME}"
echo "Run '${BINARY_NAME} --help' to get started!"
